<a href="https://colab.research.google.com/github/mhoyor/Alright-Gadget/blob/main/notebooks/00_data_prep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
  %cd /content
  !rm -rf ckd-risk-app
  !git clone https://github.com/mhoyor/ckd-risk-app.git
  %cd /content/ckd-risk-app

/content
Cloning into 'ckd-risk-app'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 20 (delta 6), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (20/20), 11.88 KiB | 347.00 KiB/s, done.
Resolving deltas: 100% (6/6), done.
/content/ckd-risk-app

In [16]:
import pandas as pd
from data_prep import load_data, FEATURES, LEAKAGE
d = load_data()

In [17]:
d["all"].shape

(200, 29)

In [18]:
d['all'].head()

,bp,bp limit,sg,al,class,rbc,su,pc,pcc,ba,...,htn,dm,cad,appet,pe,ane,grf,stage,affected,age
0,0,0,3,1,1,0,0,0,0,0,...,0,0,0,0,0,0,9.0,s1,1,0
1,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,9.0,s1,1,0
2,0,0,1,4,1,1,0,1,0,1,...,0,0,0,1,0,0,5.0,s1,1,0
3,1,1,1,3,1,0,0,0,0,0,...,0,0,0,0,0,0,5.0,s1,1,0
4,0,0,2,0,1,0,0,0,0,0,...,0,1,0,1,1,0,5.0,s1,1,1

**How many CKD vs non-CKD patients**

In [19]:
d["all"]["class"].value_counts()

class
1    128
0     72
Name: count, dtype: int64

In [21]:
pd.crosstab(d["all"]["class"], d["raw"]["affected"])

affected   0    1
class
0         72    0
1          0  128

In [22]:
pd.crosstab(d["all"]["class"], d["raw"]["stage"])

stage  s1  s2  s3  s4  s5
class
0      45  23   0   4   0
1       9  12  31  41  35

In [23]:
d["all"].isna().sum()[d["all"].isna().sum() > 0]

grf    1
dtype: int64

In [24]:
print(len(FEATURES))
print(FEATURES)

25
['bp', 'bp limit', 'sg', 'al', 'rbc', 'su', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sod', 'sc', 'pot', 'hemo', 'pcv', 'rbcc', 'wbcc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'age']

In [25]:
print(d["train"].shape, d["test"].shape)
print(d["train"]["class"].value_counts().to_dict())
print(d["test"]["class"].value_counts().to_dict())

(160, 29) (40, 29)
{1: 102, 0: 58}
{1: 26, 0: 14}